[package]
name = "vmiks"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.33.3", features = ["persistence"] }
egui = "0.33.3"
ks-common-generic = { git = "https://github.com/lexag/ks-common" }
ks-common-ui = { git = "https://github.com/lexag/ks-common" }
serde = { version = "1.0.229", features = ["derive"] }
